# -*- coding: utf-8 -*-
"""advanced_project_part_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HsfIOw6he3vUquPtvwR3bHTibc_nCR6-
"""

!pip install pandas matplotlib seaborn

from google.colab import files
import pandas as pd

uploaded = files.upload()

df = pd.read_excel(next(iter(uploaded)))
print("Dataset loaded successfully!")

df.head()

print("Dataset Info:")
print(df.info())

print("\nDataset Description:")
print(df.describe())

print("\nMissing Values:")
print(df.isnull().sum())

genre_revenue = df.groupby('genres')['revenue'].sum().reset_index()

genre_revenue = genre_revenue.sort_values(by='revenue', ascending=False)

print("\nTotal Revenue by Genre:")
print(genre_revenue.head())



import plotly.express as px

genre_popularity = df.groupby('genres')['popularity'].mean().reset_index()
genre_popularity = genre_popularity.sort_values('popularity', ascending=False)

fig = px.funnel(genre_popularity, x='popularity', y='genres', title="Popularity by Genre")

fig.update_traces(marker=dict(color='purple'), textinfo='value+percent previous')

fig.show()

import matplotlib.pyplot as plt

genre_revenue = df.groupby(['genres'])['revenue'].sum()

plt.figure(figsize=(10, 6))
genre_revenue.plot(kind='bar', stacked=True, color='lightcoral', edgecolor='black')
plt.title('Revenue Share by Genre')
plt.xlabel('Genres')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Plot revenue share by genre
plt.figure(figsize=(8, 8))
plt.pie(df['revenue'], labels=df['genres'], autopct='%1.1f%%', startangle=140)
plt.title('Revenue Share by Genre')
plt.show()